[mgr]
append_keymap = [
  { on = [
    "g",
    "p",
  ], run = "cd ~/Pictures", desc = "Go ~/Pictures" },
  { on = [
    "g",
    "u",
  ], run = "cd ~/u", desc = "Go to university" },
  { on = [
    "g",
    "w",
  ], run = "cd ~/w", desc = "Go to work" },
]
